### ISSUE TITLE
Performance very slow with lots of points

### ISSUE THREAD

**Issue by craigsoules** [c3js/c3#1075]
When plotting fine-grained data in a line chart (e.g., 3000 points) the responsiveness of the chart is extremely poor.

**Comment by aendrew** [comment]
Try plotting fewer points? :sweat_smile: 

j/k It should be able to handle that decently well on a modern machine (wouldn't try it on mobile, though). Could you please provide a bit more information re: your setup? Is [`transition`](http://c3js.org/reference.html#transition-duration) at a value other than `0`? Is [`interaction`](http://c3js.org/reference.html#interaction-enabled) enabled? Disabling transition and interaction should improve performance significantly, BTW.

**Comment by craigsoules** [comment]
It's the interaction hover-over that is particularly slow :-(

On Sat, Apr 11, 2015 at 4:29 PM, Ændrew Rininsland <notifications@github.com
> wrote:

> Try plotting fewer points? [image: :sweat_smile:]
>
> j/k It should be able to handle that decently well on a modern machine
> (wouldn't try it on mobile, though). Could you please provide a bit more
> information re: your setup? Is transition
> <http://c3js.org/reference.html#transition-duration> at a value other
> than 0? Is interaction
> <http://c3js.org/reference.html#interaction-enabled> enabled? Disabling
> transition and interaction should improve performance significantly, BTW.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/masayuki0812/c3/issues/1075#issuecomment-91944949>.
>



-- 
Craig Soules
Natero, Founder & CEO
www.natero.com | 650-308-9135

**Comment by aendrew** [comment]
Ah, yep — there's probably something that can be done in the library to improve interaction performance-wise, but realise you're asking a lot out of a web-browser to render something that complex and also be interactive. 

A thought: do you have any comparable benchmarks with other SVG-based JavaScript libraries, possibly [Chartist](http://gionkunz.github.io/chartist-js/), [NVD3](http://nvd3.org/) or [Dimple](http://dimplejs.org/)? If C3 is less performant in large datasets, it would be good to have an idea how much less performant it is.

**Comment by aendrew** [comment]
Here's [an example](http://jsfiddle.net/aendrew/b58gkjky/) that plots 3000 arbitrary points in a C3 graph. Can confirm it's slow on my 2013 Macbook Pro. Oddly, interaction seems to now self-disable in 4.10.0 once ~750 points have been plotted.

That said — [turning points off](http://plnkr.co/edit/fGB9TIJfJpeKCKUvxK44?p=preview) improves performance by quite a lot, because it's not having to render 3000+ circle nodes in SVG.

I haven't been able to get the performance tester on jsFiddle to work, but I might try to do a comparative thing with other SVG JS libraries once I do.

**Comment by craigsoules** [comment]
Interestingly, your second example, even set to 5000 points, is displaying
tooltips much faster than our charts with only 4000 points.  I will try
updating our C3 again, since we're on 0.4.9 and it looks like there's been
another release which may have improved performance.

Also, I notice that your chart displays the tooltip based only on the
x-position, and doesn't require hovering over a point, which probably takes
less calculation.  How is that option set, or is that also new as of 0.4.10?

Thanks!
Craig

On Sun, Apr 12, 2015 at 7:50 AM, Ændrew Rininsland <notifications@github.com
> wrote:

> Here's an example <http://jsfiddle.net/aendrew/b58gkjky/> that plots 3000
> arbitrary points in a C3 graph. Can confirm it's slow on my 2013 Macbook
> Pro. Oddly, interaction seems to now self-disable in 4.10.0 once ~750
> points have been plotted.
>
> That said — turning points off
> <http://plnkr.co/edit/fGB9TIJfJpeKCKUvxK44?p=preview> improves
> performance by quite a lot, because it's not having to render 3000+ circle
> nodes in SVG.
>
> I haven't been able to get the performance tester on jsFiddle to work, but
> I might try to do a comparative thing with other SVG JS libraries once I do.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/masayuki0812/c3/issues/1075#issuecomment-92076345>.
>



-- 
Craig Soules
Natero, Founder & CEO
www.natero.com | 650-308-9135

**Comment by balsa0** [comment]
Hi there!
I found something interesting about this problem:
- with < 1000 points tooltip is displayed properly
- after a point after ~1070 points tooltip disappears strangely
I found that in this case, if <body> or <html> or any parent container overflows the screen (only x-overflow, not y) tooltip disappears. If i force the overflow to "hidden", tooltip comes back (without reload).

Thanks for your quality work!
Regards!
Balsa0

**Comment by Funfun** [comment]
it may be could be helpful if we emulate the bind native function.

https://github.com/Funfun/c3/commit/d547a8b1423bba7bf4c540067a8181c0e6c389c4
https://gist.github.com/Funfun/d13978465d2b82690d69

in chrome, 15s vs 22s for 30000 points.

**Comment by murenrb** [comment]
Hey all,
I want to propose a different way of handling this issue. Displaying 3000 points should never be very useful because it exceeds the resolution of any screen. IE, what does it mean to display 3000 points  on a screen that is only displaying 100-200ppi. I think an alternate solution might be to have some sort of re-sampling before rendering. I have 0 experience with javascript, but it seems like it would be fairly straight-forward to re-sample the points to go from 3000 points to something reasonable. 

Lets limit ourselves to 1920pixels on the screen. It's unlikely that any plot would take up more than 80% of the screen. That leaves us 1530 pixels that can be applied to points. This is a first cut limit that the graph should never exceed or else data will already be lost so it may as well not try to plot the data anyway. IE, the re-sampling is already happening somewhere and we (or at least I) have no idea how. 

In reality 1530 is still way more points then we need as we don't really need each pixel to get a point. I ran a few examples and I would argue that the most points that ever need to be plotted on any reasonable screen is 500. That's a small number! Here is an example of a sin wave with 3000, 1000, and 430 points. 

The natural response to this might be that the responsibility of the quantity of data falls to the code generating the data. This is a valid response! But also, a very difficult problem for large real-time datasets. For example, in a dashboard we often want to see the most recent data in detail. So, a user might use something like a subplot to zoom in on the most recent hour of operation. If only enough data is being sent to populate the full time scale (which may be a year, a week, or a day) then there would never be enough data to populate the zoomed timescale. Thus, this is really a plotting issue. 

How hard would it be to only propagate the svg with a limited dataset? Could one input to the library be a limited number of points to plot allowing a user to set a maximum number of points to display on any plot? IE, if a limit of 500 were set, the plot would display 500 points at any zoom level. This would allow the page to remain responsive. 

Like I said above, I don't know anything about javascript. Nor do I really understand what step is causing c3.js to perform slow. But my guess is it is the rendering of so many points. Instead of figuring out how to render those points faster, perhaps it is valuable to think about the merits of keeping more data on the screen than pixels. 

![screen shot 2016-05-20 at 9 21 49 am](https://cloud.githubusercontent.com/assets/7243901/15432841/124ee2d0-1e6d-11e6-9c22-694c35332ab9.png)

**Comment by craigsoules** [comment]
While I agree in concept, if I plot 4 lines on a chart with 500 points each, the problem remains.

It would also be nice to do the sampling within c3 itself and make that optional.

**Comment by murenrb** [comment]
Good point about the multiple lines. That one got by me!!

As for the optional aspect, that is what I am thinking. The user should be able to stipulate some limits and then c3 would automatically sample the data based on the zoom level. If you got clever about it you could make a dynamic sampling based on the first derivative and my guess is you could get a huge reduction in rendering load. 

Can we please switch the internet to python so I can actually contribute to this? Who has the time to learn javascript.

**Comment by pkyeck** [comment]
> Also, I notice that your chart displays the tooltip based only on the
x-position, and doesn't require hovering over a point, which probably takes
less calculation.  How is that option set, or is that also new as of 0.4.10?

Was wondering the same. Is there an option to activate that behavior?
Same charts do it like this, some only if you hover over the graph.

**Comment by mike-robertson** [comment]
To people running into @balsa0 's problem, the solution seemed to be making sure you pass data for the x columns. If you allow the default behavior (no passed x columns), it doesn't seem to work with the tooltip at larger data sizes.

**Comment by aendrew** [comment]
@murenrb's suggestions are probably the most relevant in here, and a very good point. In my (now greater since first posting in this issue) experience with SVG, any SVG with >1000 elements will be slow. Full stop. Desktop, mobile, whatever. This is _elements_, not data points — with interaction on, each data point creates anywhere from 1-3 elements, each with their own event handlers (an invisible sort of Voronoi-style grid is placed above the data points, which improves UX but at the cost of performance).

What C3 probably needs more than a bunch of micro-optimisations across the board (which it needs regardless; I've never felt the underlying lib is very optimised) is the ability to render to Canvas, or a fork of C3 intended for use with Canvas. #1436 attempted to do this but is terribly outdated.

This issue has become more about tracking weirdness with interaction than anything. As a result, am closing for now.
