### ISSUE TITLE
gradient styles in chart elements

### ISSUE THREAD

**Issue by astroanu** [c3js/c3#1098]
I know this has been asked many time. I know that the g tag  does not support css gradients. However if there was an option to define the gradient styles on the svg def and apply them would be nice. I personally don't like gradients but some people do.

**Comment by fredpyo** [comment]
(Don't know if this is the right place to ask this, perhaps it'll be better to use the [user forums](https://groups.google.com/forum/#!forum/c3js)... but here's an idea anyways)

A quick search on the issues list revelas this has already been suggested here and someone posted an example that seems to work: #519 
It requires some low level SVG knowledge and adding gradient definitions by hand, if you're comfortable with that, this can be one way to solve it in one go.

You could also try doing something like mentioned in this [stackoverflow question](http://stackoverflow.com/questions/12826604/how-to-use-svg-gradients-to-display-varying-colors-relative-to-the-size-of-the-c) answer .

If you look at the fiddle in the accepted answer, you'll see how you can create and attach gradients to elements. Since c3 is built on top of the glorious [d3js](http://d3js.org/) library, you can use those utility methods to create gradients and apply them to graphs created with c3.

Note that in the example both the gradients and the shapes are being created, what you'd want is to create the gradients and attach them to the elements that C3 already created.

Hope this helps.

**Comment by abacaj** [comment]
Following up, I have solved this problem on a project recently - if anyone is interested or curious enough I can extend the library to support it.

**Comment by michaelrodov** [comment]
This can be achieved using a SVG native <defs> and css url notation.
[Example](http://www.w3schools.com/svg/svg_grad_linear.asp)
Closing
