### ISSUE TITLE
Is this project still being actively maintained?

### ISSUE THREAD

**Issue by jpruetting** [c3js/c3#1540]
Is this project still being actively maintained?

It looks like the release cadence has slowed down considerably, the author's public activity on Github has ceased, and issues are piling up.

**Last release:** March 17th, 2015 [0.4.10](https://github.com/masayuki0812/c3/tree/0.4.10)
**Author's last activity:** October 21, 2015 [masayuki0812](https://github.com/masayuki0812?tab=activity)
**Issues:** [463 open issues](https://github.com/masayuki0812/c3/issues)

**Comment by countzen2000** [comment]
I wish I could use this library but it seems.. a bit dead. Gotta move on to something else. :(

**Comment by say8425** [comment]
I think so. But I can't find something else better.

**Comment by miguelpaz** [comment]
If its open source it means it can be supported by the community or not?

**Comment by tom-christie** [comment]
@miguelpaz Someone could fork the project and maintain it themselves. Any volunteers?

@say8425 I just came across TauCharts (https://github.com/TargetProcess/tauCharts) which looks very similar in terms of usability.  Not sure about feature parity or implementation.

**Comment by aendrew** [comment]
Howdy folks,
So, here are the issues we're facing.
1. Only @masayuki0812 and myself have write access, and I've always been more of a documentation person. The impression I've gotten from him is that he's massively busy with work (as I also am). Although he's recently been more amenable to the idea of me merging commits, I've frankly just been way too busy to do anything significant (the fact I myself am still pretty unfamiliar with and, tbth, a bit daunted by C3's internal API doesn't help either).
2. I've been utterly useless in triaging issues the last six months, which I'm very sorry for. Despite my requesting help on the Google Group previously, nobody's really offered to help manage the issue queue (though there are definitely members of the community who are helping out here and there, mainly on the Gitter channel for immediate support). 
3. The list of people with write access really hasn't grown organically to accommodate a project of this size. In all honesty, we should have 4-8 people with write access by this point, comprised of something like a "core development" subteam of 4-6 people and 2-3 documentation/issue triage people. 

re: forking the project — that's certainly an option, and one I've considered myself several times at this point. I'm [about 50% of the way through rewriting everything so it uses CommonJS modules and Webpack instead of concatenation and grunt](https://github.com/aendrew/c3/tree/webpackify), which I see as a necessarily first step towards making everything more modular and testable. I may then later rewrite everything as ES2016, using ES6 modules and language features. I've also considered rewriting considerable parts of the internals as TypeScript, though am not sure that would make the project any easier to contribute to. 

That all said, I'm still pretty hesitant to do so because I simply don't have the time to fix all of C3's problems myself and have no desire to be the primary maintainer of a fork. I still think there's a ton of life left in the project (for instance, I do a lot of stepped explanatory graphics in my work, and I haven't found anything as easy to use as C3 for when I want to do things like programmatically select data points and whatnot), but I feel everyone would probably benefit if I took a step back and let somebody else lead development on a fork, if that's what everyone in the community eventually decides to do.

My two.

**Comment by jpruetting** [comment]
This is a very common problem with open source libraries and I don't think anyone should be declaring the project 'dead' just yet. Moving the things to a dedicated Github org (c3/c3) would be a good step forward, as well as recruiting additional maintainers with commit access.

**Comment by gitawego** [comment]
i think @jpruetting 's suggestion is pretty good.

**Comment by aendrew** [comment]
@jpruetting @gitawego I'm 100% on board with moving everything to a dedicated org, have mentioned it previously in #1440. Alas, I don't have admin capabilities on the repo so we'd have to get agreement from @masayuki0812 for it to happen.

**Comment by aendrew** [comment]
@tom-christie Last I heard from him was via email in October; we had talked about organising the community more after a thread similar to this one was sent around to the Google Group. If there's some sense of consensus that the biggest thing holding back the library is it not being in its own org, I'll email him to ask about whether he'd mind doing that (I generally try to keep all project-related correspondence to GitHub as it keeps it more transparent that way and I personally find it really annoying when people email me directly about open source stuff, but at the moment email seems like the one medium he's responding to).

re: the site, is working fine for me. It's hosted on GitHub Pages so if there's a connection issue, it's more GitHub's issue.

**Comment by basilesimon** [comment]
@aendrew I'm very sad to hear that you're left on your own while the issues accumulate.
I've been a heavy user of c3 myself, but the performances issues have never been addressed, and I'm afraid I'm going to have to move on. I hope @masayuki0812 will find the time to engage with the issues or approve a new way of working that would engage more people with this nice work - the dedicated org sounds like a solid plan.

**Comment by rosorrentino** [comment]
I think this project is great and it's amazing how far it gone with so few maintainers (just read aendrew comment) 
You should add a donation button in project page, I think if all users give a little, developers would have something more to dedicate to this project.

**Comment by aendrew** [comment]
@rosorrentino That's not the worst idea; maybe something like Gratipay for bug bounties?

**Comment by mcarey1590** [comment]
I actively use c3 and believe it to be one of the best open source charting solutions out and would be willing to help with development and issues given c3 was moved to a dedicated org as mentioned.

**Comment by samedii** [comment]
@aendrew Haven't heard anything yet? Also, gratipay is a good idea

**Comment by xmehaut** [comment]
Sad to hear that the project could be down.
I've had for my own purpose created a React/Typescript C3 version based upon the C3 code. 
Maybe could it be a new start?
regards

**Comment by aendrew** [comment]
@xmehaut That looks awesome, but I don't know how compatible it is with the current direction of C3. How'd you use TypeScript with it? I've been personally considering writing a TypeScript fork, or a TypeScript definition, or something generally TypeScript-y, and would be great to not duplicate anything you've done.

Everyone — I'm going to take another stab at getting through the open PRs, which I'm merging to the `dev` branch at present (once @masayuki0812 is okay with how the code looks in that, I'll . Expect that branch to be the most modern but also the least stable.

**Comment by xmehaut** [comment]
Hi Andrew,

you can find samples in the online and ongoing (personal) doc :
http://semantix-ui.appspot.com/

See the Charts/C3 section at the bottom of the sidebar

regards
xavier

2016-02-18 14:10 GMT+01:00 Ændrew Rininsland <notifications@github.com>:

**Comment by Tropicalista** [comment]
Probably the best solution is to go with a module/plugin architecture to handle the library.

**Comment by aendrew** [comment]
Hey all — I've re-written a bunch of the lib to load modularly in CommonJS format; see [aendrew/c3#webpackify](https://github.com/aendrew/c3/tree/webpackify). It *seems* to work, even though 49/54 unit tests are currently failing. Any feedback would be great.

**Comment by bjlbernal** [comment]
Looking forward to contributing Timeline gantt charts (https://github.com/masayuki0812/c3/issues/514) when you are ready. I've never used CommonJS or AMD, is the build process the same as grunt?

**Comment by jpruetting** [comment]
It looks like @masayuki0812 has started responding to issues again.

@masayuki0812: Would you be willing to move this project over to the [c3js](https://github.com/c3js) org you created and add some additional maintainers?

**Comment by aendrew** [comment]
Everyone! I am happy to announce this project is now on the [c3js](http://github.com/c3js) GitHub organisation! Many thanks to @masayuki0812 for moving it there!

To that end, I'm going to start organising issue triage. If you want to help churn through the ~500 open issues, tagging good issues and closing irrelevant ones, please let me know!

**Comment by thomblake** [comment]
Probably this issue should be closed then?
