### ISSUE TITLE
Optionally have line segments drawn through null points.

### ISSUE THREAD

**Issue by dopry** [c3js/c3#1574]
Currently, if you have multiple series  and one contains a f(x) == null then a segment is not drawn between the adjacent points.. It would be nice to have the option to have a line drawn though the null point between the adjacent points with values.

**Comment by aendrew** [comment]
@dopry I think the reason why it's like that is due to it being confusing if a line is drawn through a non-existent point — if you draw the line through the null point, it looks like there's data there, when there isn't.

Closing as wontfix, please feel free to comment if you think I'm misunderstanding the issue.

**Comment by dopry** [comment]
I'm not proposing it as a default behavior, but an option. There are times when you want to interpolate through missing data. 

As for visual confusion, there are number of ways to highlight interpolated segments such as changing the stroke to dashed or removing not displaying a  point at f(x) == null. 

It is kind of a requirement of my current project. I'm currently comparing a number of sparse linear series side by side and they end up just being a  bunch of dots or with maybe a segment or two in each series.

**Comment by aendrew** [comment]
Interesting; I see your point. Reopening!

**Comment by panthony** [comment]
From my understanding, this is possible using the [connectNull](https://c3js.org/reference.html#line-connectNull) option.

Feel free to reopen if misunderstood.
