### ISSUE TITLE
Area-spline incompatible with dashed regions

### ISSUE THREAD

**Issue by fabiopedrosa** [c3js/c3#1684]
The moment I make a area chart use area-spline type, the lines don't become smoothed if there's any regions used.

**Comment by jorgtron** [comment]
I would also like to see this solved :D

**Comment by michaelrodov** [comment]
It's quite possible that could be a bug, but it's really hard to verify it without more information. 

We get a lot of reports and the more info you give us, the more likely we'll be able to address it in a timely fashion.

Please [read the contributing guidelines](https://github.com/masayuki0812/c3/blob/master/CONTRIBUTING.md), then add the following information to your issue:

-  Operating system and web browser (with version)
-  What version of the library
-  If you were doing anything unusual, like using C3 in conjunction with a particular library or framework
-  Ideally, a [JSFiddle](https://jsfiddle.net/) example depicting the specific problem really helps us out. 
	* [Use this JSFiddle template](https://jsfiddle.net/aendrew/L4ocdkcq/)


Thank you for your cooperation — we rely on users like you to help make C3 the best charting library it can be!>

**Comment by javflores** [comment]
Hi there @jorgtron and @michaelrodov .
I am having the issue with spline lines as well.
I don't think it is an issue but probably a feature not yet implemented. I'll try to explain...

In c3 there is the following function: ```generateDrawLine```
Inside we have a check like the following:
```
if ($$.isLineType(d)) {
                if (config.data_regions[d.id]) {
                    path = $$.lineWithRegions(values, x, y, config.data_regions[d.id]);
                } else {
                    if ($$.isStepType(d)) { values = $$.convertValuesToStep(values); }
                    path = line.interpolate($$.getInterpolate(d))(values);
                }
            }
```

The last part, interpolation, is the area where splines are created.
Basically if you have a region for that parameter id, it will go and create a line with region.
LineWithRegions basically generates a standard line given the different points (x,y) and joins them together.

I have tried to implement this feature myself by trying to check if we have a spline and a region define, doing the interpolation.
Unfortunately I'm struggling a bit, mostly because of my lack of knowledge in C3. 
The approach I was following to solve the problem will be to create a path like this:
```
<path d="path of segments" stroke-dasharray="path for dashed region"/> 
```
The second part of the path will be dashed.
This of course won't allow to set any other customization for the different regions, like providing custom css classes.

Not sure if I'm explaining correctly.

**Comment by jcelletti** [comment]
var chart = c3.generate({
    data: {
        columns: [
            ['data1', 30, 200, 100, 400, 150, 250],
            ['data2', 50, 20, 10, 40, 15, 25]
        ],
        type:'spline',
        regions: {
            'data1': [{'start':1, 'end':2, 'style':'dashed'},{'start':3}], // currently 'dashed' style only
            'data2': [{'end':3}]
        }
    }
});

this repro happens with splines in general, taken from the regions example and just add spline or area-spline as the type

**Comment by riskgod** [comment]
I met the same problem, anyone fix it ?

**Comment by riskgod** [comment]
> var chart = c3.generate({
> data: {
> columns: [
> ['data1', 30, 200, 100, 400, 150, 250],
> ['data2', 50, 20, 10, 40, 15, 25]
> ],
> type:'spline',
> regions: {
> 'data1': [{'start':1, 'end':2, 'style':'dashed'},{'start':3}], // currently 'dashed' style only
> 'data2': [{'end':3}]
> }
> }
> });
> 
> this repro happens with splines in general, taken from the regions example and just add spline or area-spline as the type

it not resolve the problem~

**Comment by riskgod** [comment]
> <

after debug I don't think the problem is here

**Comment by kt3k** [comment]
Confirmed with the latest version (v0.6.12).
repro: https://codesandbox.io/s/62pojk0843

**Comment by riskgod** [comment]
> Confirmed with the latest version (v0.6.12).
> repro: https://codesandbox.io/s/62pojk0843

The same problem here, this version didn't fix this~
