### ISSUE TITLE
mouseover doesn't fire if xSort is false and only single data point plotted

### ISSUE THREAD

**Issue by mrnosal** [c3js/c3#1745]
In a bar chart, if data.xSort is set to false and you are passing in only a single data column in, then the mouseover function isn't triggered when moving from bar to bar. Because xSort is set to false, c3 thinks it is dealing with multipleXs. `$$.isMultipleX()` returns true if xSort is false, so `$$.generateEventRectsForMultipleXs()` gets called. That function compares `closest.id !== $$.mouseover.id` yet since there is only one data column, the id values will always be the same. 
http://codepen.io/mrnosal/pen/gMmzMK
c3 v0.4.11

**Comment by nbdavies** [comment]
I saw that the mouseover event was only firing once per X value, and not re-firing when the cursor visited different Y values for that X value.

Adding `data.xSort: false` appears to yield better behavior. The xSort option ought to be documented though. Other than incidentally fixing this mouseover issue, I have no idea what its intended purpose is.

**Comment by nbdavies** [comment]
I might have missed the point of the issue before, but I'm seeing it now... 

This isn't even limited to having a single data series plotted. If your bars are grouped/stacked, with the same series on the bottom, then your cursor can travel from one bar to another bar of the same series via the X axis, and the mouseover/mouseout events do not get triggered. However, the tooltip does go away and come back with new values.

There are two pieces causing this:

1. The mouseout event on the event rectangle isn't triggering the data_onmouseout callback and also doesn't reset `$$.mouseover`. 

2. When the cursor reenters the grid onto a different bar, `$$.mouseover` doesn't correctly register it as a different value, and so your mouseover callbacks don't get triggered. The problem seems to be the maintenance of `$$.mouseover` in c3/interaction.js. When my mouse is over the second bar of the graph, `$$.mouseover` is:

    { id: "dollars", index: 0, name: "dollars", value: 4396, x: 0 }

I have a fix for both of these things that I'll create a PR for.
