### ISSUE TITLE
Sort order for stacked bar charts

### ISSUE THREAD

**Issue by pchaganti** [c3js/c3#1810]
The order configuration being set to 'asc' or 'desc' does not seem to actually sort the values in a stacked bar. Is there a different way to do this? This is one of the things that we could never do accurately with Highcharts, hence looking into c3js.

The order in the screenshot below is set to 'asc'.
![screen_shot_2016-08-17_at_3_44_40_pm](https://cloud.githubusercontent.com/assets/6500/17750683/b43cc5a2-6491-11e6-95d3-4b501cb7b8f3.jpg)

thanks for your help!

**Comment by panthony** [comment]
That's because the `order` configuration does not sort the values in each stack.

Each serie (cyan, grey, etc.) is reduced to a sum, then sorted, then each stack of the bar will respect this order so that each category is always in the same position in the stacked bar.

I do not think sorting each stacked bar based on value is possible.

**Comment by pchaganti** [comment]
Thanks!
