### ISSUE TITLE
Adding a class to a parent container does not carry the style to the legend

### ISSUE THREAD

**Issue by Java1Guy** [c3js/c3#1846]
I created a style class:
.chart-legend-small {
    font-size: 10px;
}
And put it on virtually all the outer divs of my chart.  The font-size was not propagated down to the legend fields.
`                <div class="detail_subcontainer chart-legend-small">
                  <div class="row">
                    <div class="col-md-12" style="display:table;">
                      <span style="text-align:center;font-weight:bold;font-size:10px;display:table-cell;">Purchase Composition</span>
                    </div>
                  </div>
                  <div class="row chart-legend-small">
                    <div class="col-md-12 chart-legend-small" style="padding:0 0 0 0;">
                      <div id="purchaseComposition" class="chart-legend-small"></div>
                    </div>
                  </div>
                </div>
              </div>
 `
<img width="892" alt="developer_tools_-_http___127_0_0_1_8080_lead-generator_hawaii_details_0" src="https://cloud.githubusercontent.com/assets/69846/18647613/ff20b8d4-7e73-11e6-9a50-c95c145a183f.png">

I presume this is a bug since it was the method prescribed for accomplishing this task.

**Comment by aendrew** [comment]
Please don't open new issues when I've explicitly told you what you're asking is a support request and this is not the proper channel to do so...

To expand upon what I wrote earlier — assign a class to the parent container, and then write a CSS override for the element you're wanting to modify. Instead of merely setting font size on the parent container, set a class on the parent container and target the class of the child element.

So instead of `.chart-legend-small { ... }`, write `.chart-legend-small .c3-legend-item { ... }`, replacing the ellipses with your overrides.

SVG CSS works pretty similarly to HTML CSS. If with CSS more generally, I recommend pursuing any of the multitude of resources available — here's a [free course from CodeAcademy](https://www.codecademy.com/courses/css-coding-with-style/0/1).

**Comment by Java1Guy** [comment]
Thanks for the more detailed explanation... I opened the first issue because I thought it was a feature request for which I did not see any references in the forum threads, and the second because I thought it was a bug report.
