### ISSUE TITLE
Failing to parse moment dates

### ISSUE THREAD

**Issue by dabada83** [c3js/c3#1873]
#@Tryton web client Sao use C3 to render graph views.

With version 0.4.10 timeseries works fine.

When we update C3 version from 0.4.10 to 0.4.11,
at display graph type line with timeseries, browser
show this error:
c3.js:1048 Failed to parse x '1478062800000' to Date object

We use momentjs date object to populate data.

![0_4_10_version](https://cloud.githubusercontent.com/assets/211490/19927695/d73c8808-a0c8-11e6-8830-048cd9f7b186.png)
![0_4_11_version](https://cloud.githubusercontent.com/assets/211490/19927699/dd0d1fc2-a0c8-11e6-9ab4-48d9d6037f1d.png)
![cut](https://cloud.githubusercontent.com/assets/211490/19927706/e2ac32ba-a0c8-11e6-9f34-558076cab75e.png)

**Comment by dabada83** [comment]
Minimal test case...

Succesful with 0.4.10 version 
http://jsfiddle.net/dabada83/gs14036o/3/

Fail with 0.4.11 version
http://jsfiddle.net/dabada83/kzzzp70s/3/

**Comment by conceptualspace** [comment]
it is due to https://github.com/c3js/c3/pull/1121/commits/5c443a6dcc0cca680f5b025b8ecf1ab27ae2e107

since moment date is an object, none of these date conditions are true:

```
 c3_chart_internal_fn.parseDate = function (date) {
     var $$ = this, parsedDate;
     if (date instanceof Date) {
          parsedDate = date;
      } else if (typeof date === 'string') {
          parsedDate = $$.dataTimeFormat($$.config.data_xFormat).parse(date);
     } else if (typeof date === 'number' && !isNaN(date)) {
          parsedDate = new Date(+date);
      }
      if (!parsedDate || isNaN(+parsedDate)) {
         window.console.error("Failed to parse x '" + date + "' to Date object");
     }
     return parsedDate;
 };
```

in v4.10, the object was caught by `else if (typeof date === 'number' || !isNaN(date))...`, and was successfully converted: `new Date(+date)`

so this bug in v4.10 was actually also a feature? can we support [Moment](https://github.com/moment/moment/) again please?
