### ISSUE TITLE
Replace all expect(true).toBeTruthy() blocks with beforeEach blocks

### ISSUE THREAD

**Issue by aendrew** [c3js/c3#2047]
See https://github.com/c3js/c3/issues/1843#issuecomment-304484663.

**Comment by aendrew** [comment]
I've done this now but beforeEach seems to break things, there's some weird scoping considerations throughout all the unit tests.

**Comment by kt3k** [comment]
Maybe we should use `beforeAll` instead of `beforeEach` in most places because each test cases are depenedent of the cases before it (This is not a good way to write tests IMO.). We need to keep the state of charts between test cases and setting data in `beforeEach` wipes the data in each case and breaks the tests (probably).
