### ISSUE TITLE
Timeseries transition should scroll?

### ISSUE THREAD

**Issue by smeyfroi** [c3js/c3#207]
I'm using c3 to visualise a timeseries, loading new data with the load() method to update the chart with the last so-many points. The transition animates each x (time) point into its new position on the y axis. Given that, with a timeseries, each update pushes the time basis on by some amount, it seems like the transition should be a scrolling animation for the entire chart, not a point-by-point transition.

Is it possible to transition a timeseries chart with scrolling along the time axis?

**Comment by MythriManjunath** [comment]
@masayuki0812 
c3.js - flow api with REST API do not refresh the chart - angular 2 + typescript

Hi, I am  trying to update c3 chart dynamically for every few minutes or seconds. The JSON data is obtained from REST API URL which is dynamic. The data points int the chart should be updated dynamically as soon as the new JSON data comes in. The window of the chart should keep moving. I am using angular 2 and typescript. I referred this  example http://c3js.org/samples/api_flow.html and http://c3js.org/samples/data_load.html. The chart will not update dynamically. In order to see new values, I need to refresh it manually. Here is the sample code. 
```
private chart: any;
this.chart = c3.generate({
   data: {
        url:  '/api/systemvalues',
        mimeType: 'json',
        keys: {
          x: 'timesatmp',
          value: ['uploadValue'],
        },
 axis: {
    x: {
      type: 'timeseries',       
});

  var vm = this;
 setTimeout(function () {
    vm.chart.flow({
             url: '/api/systemvalues',
        mimeType: 'json',
        keys: {
          x: 'timestamp',
          value: ['uploadValue'],
        },
        duration: 1000
    })
}, 2000);
```
