### ISSUE TITLE
Nav tabs and C3js

### ISSUE THREAD

**Issue by ja153903** [c3js/c3#2107]
I have two charts, each of which is associate with a Bootstrap tab. One initially has the active class and is sized correctly. However, upon clicking the other tab, I see that the charts are not of the right size as they end up being the length of my browser when I intended it to be about half that size.

Is there a fix for this?

**Comment by panthony** [comment]
No really familiar with bootstrap's css but the chart needs to be visible in order to be sized correctly.

If it has 'display:none;' it cannot work.

A workaround I use to do is to replace 'display:none;' by something like 'position: absolute;left:-999999px;bottom:-999999px;'.

Basically, displaying it far off screen.
