### ISSUE TITLE
Using Time in minutes on X axis (C3JS)

### ISSUE THREAD

**Issue by mgahiwal** [c3js/c3#2116]
I have to use time in minutes on C3JS time series chart. So how should i add this?

**Comment by samskrithib** [comment]
I think this will be helpful
http://c3js.org/reference.html#axis-x-tick-format

http://jsfiddle.net/8u687L3n/1/

**Comment by Omar-Aziz** [comment]
Can you use timeseries and also data from csv? I have lots of data so I'm getting it from csv (url: 'data.csv') but I also want to use a time series with 12 hours interval and the total interval is 5 days. I tried many things but it doesn't work. It seems like I either have to use data from the same script (not csv) in order to use timeseries.

`    var chart = c3.generate({
        bindto: '#chart',
        data: {
            url: '../data_testing.csv',
            x: 'x',
            xFormat: '%Y-%m-%d',
            columns: [
                ['x', '2016-8-10', '2016-8-10', '2016-8-10', '2016-8-10', '2016-8-10', '2016-8-10']
            ],
            type: 'line'

        },

        axis: {
            x: {
                type: 'timeseries',
                localtime: false,
                tick: {
                    culling: true,
                    fit: true,
                    culling: {
                        max: window.innerWidth > 700 ? 8 : 5
                    },
                    format: '%Y-%m-%d' // %H:%M:%S
                }
            },
            y: {
                max: 55,
                min: 6
            }
        }
    });

    require(["d3", "c3"], function (d3, c3) {
        c3.generate({

        });
    });    `
