### ISSUE TITLE
Bar charts throw an error if hovered while loading

### ISSUE THREAD

**Issue by joankaradimov** [c3js/c3#2451]
Steps to reproduce:
* Open [the data load demo](https://c3js.org/samples/data_load.html).
* Open the browser console.
* Flail your mouse furiously left and right as the data changes.
* The moment a bar chart appears an exception is thrown.
  - on Chrome it's an `INDEX_SIZE_ERR` coming from the polyfills.
  - on Firefox it's a native `IndexSizeError: Index or size is negative or greater than the allowed amount`

On the demo page the code is minified, but a non-minified 0.6.6 produces a stack trace that looks something like this:
```
window.SVGPathSegList._checkValidIndex @ polyfill.js:1175
window.SVGPathSegList.getItem @ polyfill.js:1181
ChartInternal.isWithinBar @ shape.bar.js:125
(anonymous) @ data.js:334
ChartInternal.findClosest @ data.js:332
(anonymous) @ data.js:318
ChartInternal.findClosestFromTargets @ data.js:317
(anonymous) @ interaction.js:67
(anonymous) @ on.js:30
```

I cannot provide a good stack trace for 0.6.7 as the distribution no longer includes the original `src` directory.

The reason appears to be a call to `that.pathSegList.getItem(0)` inside `ChartInternal.isWithinBar` when `that.pathSegList` has no elements.

Environment:
* **C3 version**: 0.6.6, 0.6.7 [and also some older versions]
* **D3 version**: 5.5.0 [and also some older versions]
* **Browser**: Chrome 67, Firefox 59.0.2
* **OS**: Windows 10

**Comment by nmaniwa** [comment]
I have the same issue. When I encounter this issue, the following variable, `this.numberOfItems` becomes zero.
```
      window.SVGPathSegList.prototype._checkValidIndex = function (index) {
        if (isNaN(index) || index < 0 || index >= this.numberOfItems) throw "INDEX_SIZE_ERR";
      };
```

**Comment by IceCreamYou** [comment]
We encountered this in production today with C3 0.7.0 and D3 5.9.2 and can reproduce it on the C3 examples site in Chrome and Firefox. Fixing the point that throws the error seems simple enough (the line is [here](https://github.com/c3js/c3/blob/master/src/shape.bar.js#L121) and could probably be fixed by returning early if `that.pathSegList.numberOfItems < 1`) but it seems to me that doing so is likely to reveal other issues. Probably [interaction.js](https://github.com/c3js/c3/blob/master/src/interaction.js#L56) should check if anything interact-able has been rendered but I am not sure at what point interaction should become possible or how that would affect other types of charts or charts with animations.

**Comment by panthony** [comment]
This issue was [fixed](https://github.com/c3js/c3/blob/master/src/shape.bar.js#L122-L125) by ensuring the path as at least 2 members.

If another problem arise elsewhere we should open another issue 👍
