### ISSUE TITLE
Timeseries chart issue

### ISSUE THREAD

**Issue by amitabhdas** [c3js/c3#250]
http://c3js.org/samples/timeseries.html 
When we have a date time specified in the format "2014-05-14 21:05:00" it does not generate the chart in IE / Safari. it shows up as NaN.

**Comment by peterlauri** [comment]
As of version 0.3.0 data.x_format is changed to data.xFormat. Reference:

https://github.com/masayuki0812/c3/releases/tag/0.3.0

**Comment by Zerim** [comment]
> Without this option, the date string must be able to be parsed by Date.parse().

@masayuki0812 My datestring in ISO 8601 format can be parsed by Date.parse but is not being recognized by C3 time series chart.

From a quick look at the source, the issue seems to be that if the date value is a string, then you *always* run it through d3.time.format.parse, which strictly enforce the format specified that you pass in from xFormat.

See: https://github.com/c3js/c3/blob/223404a79246c61d150d8a209dbdc81f6955083b/src/core.js#L1037

I would expect the correct behavior to try `new Date(date)` as a fallback in all cases, not just when date is of type number.

Let me know if you'd like me to submit a PR.
