### ISSUE TITLE
Memory leak when switching tabs

### ISSUE THREAD

**Issue by NickJSpencer** [c3js/c3#2558]
* **C3 version**: 0.6.12
* **D3 version**: 5.7.0
* **Browser**: Chrome Version 68.0.3440.106
* **OS**: macOS High Sierra Version 10.13.6

Every so often, when I switch tabs away from the one using the c3 library, the javascript memory will begin to increase.

<img width="486" alt="screen shot 2019-01-07 at 3 15 02 pm" src="https://user-images.githubusercontent.com/22459831/50798989-2876ac00-128f-11e9-9923-eb68cdbfefd3.png">

I have narrowed this down to the c3 library scheduling transitions while away from the tab. I can't imagine this is a problem in my codebase because I never specify transitions on any c3 objects. Below are some images that might be helpful!

Screenshot of where the memory leak occurs. Note the array of scheduled transitions is very large.
<img width="1189" alt="screen shot 2019-01-07 at 3 12 37 pm" src="https://user-images.githubusercontent.com/22459831/50798885-c027ca80-128e-11e9-80ea-de80e2e48dc8.png">

Screenshot of what one of the scheduled transition objects looks like:
<img width="335" alt="screen shot 2019-01-07 at 3 16 30 pm" src="https://user-images.githubusercontent.com/22459831/50802789-9d9cae00-129c-11e9-983c-824935e279d8.png">

Screenshot of the memory snapshot on chrome tools if the memory leak is happening (~3 mins tabbed out of the tab with the leak):
<img width="1241" alt="screen shot 2019-01-07 at 4 45 17 pm" src="https://user-images.githubusercontent.com/22459831/50802836-dfc5ef80-129c-11e9-99b0-fb24ba055f21.png">

Screenshot of the memory snapshot on chrome dev tools if the memory leak doesn't occur as a reference:
<img width="1241" alt="screen shot 2019-01-07 at 4 49 45 pm" src="https://user-images.githubusercontent.com/22459831/50802809-c15ff400-129c-11e9-96d6-2cc49d0a575a.png">

**Comment by xdev-developer** [comment]
yeah, same with linux chrome.

**Comment by pstromberg98** [comment]
Ran into this as well. Looking more into it, I found out why (in my case) the `schedules` dictionary endlessly builds while tab is inactive. This is my first time looking into this library so I may have a few details wrong or missing due to my lack of understanding the entire c3 project.

The method that I found that is responsible for endlessly adding to the `schedules` dictionary is the `generateWait()` on the `ChartInternal` prototype in the c3.js file. If I understand correctly, this function returns another function that schedules the transitions (added through the function's add method), checks every 50ms if all transitions are done, then calls the callback passed in.

The `generateWait` method is called on redraw. And it seems there is even a check to see if the tab is active `$$.isTabVisible()`. But that check doesn't catch all cases. C3 is using d3-transition for its transitions, which uses d3-scheduler, which in turn uses d3-timer. More importantly, d3-timer uses `requestAnimationFrame` (if available) to clock itself. When the tab is inactive, `requestAnimationFrame` will either not tick (which is what I am seeing) or will tick non-consistently (varys between browsers). If the user navigates away from the tab while transitions are being scheduled and checked by `generateWait`, d3-timer stops ticking (meaning d3-schedule and d3-transitions are paused and won't finish), but the setInterval continues to call `t.transition` (adding to the scheduler) because the transitions won't be finished until the timer starts ticking again. Give it some time, and you will get an out-of-memory crash.

To easily replicate this, animate your chart with a longer duration transition. After the animation starts, navigate to another tab. If you go look into the c3 source and put a breakpoint in the generate wait or scheduler, you will see that it keeps calling the `transition()` and adding to the scheduler, but will never handle/process those queued up tasks. Once you navigate back to the inactive tab, the scheduler will immediately start processing those queued up tasks, and if it is enough tasks, the ui will be blocked and will only show a blank white screen.

I will be submitting a pull request with the fix soon

**Comment by queimadus** [comment]
Seems like #2589 fixes this issue for long-duration animations.

Unfortunately, it seems like periodic calls to `chart.load` while the tab is in the background will still continue to leak memory as some `transition().duration()` methods will still be called and enqueued in `d3`'s `scheduler/timer` until the tab is focused again. E.g. `ChartInternal.prototype.showTargets`.

Should `c3` handle this case too, or should it be the responsibility of the user to ensure that `load` isn't called while the tab isn't focused?

**Comment by queimadus** [comment]
What do you think @pstromberg98?

**Comment by pstromberg98** [comment]
@queimadus If somebody was calling `chart.load` on an interval while the tab is inactive, it would definitely be leaking memory. But I would find it weird if a user was calling `chart.load` using something like `setInterval` (which would effectively be recreating the issue this PR fixes). Other than `setInterval` there isn't many ways to asynchronously call `chart.load` while the tab is inactive. I could see things like handling location change, handling socket events, etc. And if `chart.load` was being called when handling those events, those events would have to fire thousands of times before it would become a problem.

That being said, I don't think it would hurt to protect users of this though. In fact, the `ChartInternal.prototype.redraw` has protection against queuing items while the tab isn't visible. Even though only a couple users (probably following bad practice), if any, would cause a memory leak by calling `chart.load` thousands of times when the browser is blurred, a check in `c3` wouldn't hurt.

**Comment by queimadus** [comment]
I'm not sure if it's such an unusual situation. I think a first naive implementation may easily stumble into this problem. As you said, creating a `setInterval` to keep the chart data up to date with the server and simply having the tab out of focus will trigger this.

**Comment by pstromberg98** [comment]
@queimadus Yeah and maybe it isn't an unusual situation. I can't say for sure. But I don't think it is the libraries responsibility to check. There was even an [issue created](https://github.com/d3/d3-timer/issues/34) about fixing this in d3 and they said to use `d3.interval` instead of `setInterval`, as it would handle inactive tabs.

But I am not against `c3` making sure the tab is active before calling d3 transitions. I think it would be a good protection. I was just laying out my thoughts on the matter.

**Comment by queimadus** [comment]
I understand your position and I think it makes sense. 
Of course I now safe guard my usage of `c3` with tab inactivity checks. I just raised the issue so other people could get to the solution sooner or even not experience this at all!

Thanks for your input @pstromberg98 :)
