### ISSUE TITLE
Can't define point sizes for different graphs

### ISSUE THREAD

**Issue by rassie** [c3js/c3#463]
Current syntax for points seems to be

```
c3.generate({
...
    point: { 
       show: true,
       r: 15 
    },
...
});
```

However, it might be useful to hide points for certain graphs, analogous to other settings, i.e.

```
c3.generate({
...
    point: { 
       data1: {
           show: true,
           r: 15 
       }
       data2: {
           ....
       }
    },
...
});
```

Currently, the second syntax does not work, but I think it should.

**EDIT**: It seems `point { r: function() { ... }}` works, so this issue is not as urgent as I thought it might be :-)

**Comment by macgyver76** [comment]
@rassie, @masayuki0812 How do you define different point sizes for different graphs? I'm trying to set it like this 
```
c3.generate({
...
    point: { 
       data1: {
           r: function(){
                return 2;
           }
       }
       data2: {
           r: function(){
                return 3;
           }
       }
    },
...
});
```

... but it doesn't work. Or am I missing something?

**Comment by aendrew** [comment]
@macgyver76 `r` is a child of `point`; not of each `datum`. It's not really documented, but you can supply a function instead of an integer and conditionally return size based on the first argument (which is an object containing the datum id.)

See [this Plunker](http://plnkr.co/edit/eheEaiVRHRnUEovEbEiz?p=preview).
