### ISSUE TITLE
integer only of the x,y axis

### ISSUE THREAD

**Issue by wayou** [c3js/c3#623]
how to make the axis tick to be integer only?
![qq 20141015141217](https://cloud.githubusercontent.com/assets/3783096/4641169/ab6869c0-5432-11e4-858c-e65eb8475ee2.jpg)

what I have tried is to use the tick option:

``` js
tick: {
    format: function(x) {
        return (x == Math.floor(x)) ? x : "";
    }
}
```

this can make the label only show integer, but the divid line on the axis still exits.
![qq 20141015141829](https://cloud.githubusercontent.com/assets/3783096/4641796/c5d800f4-543c-11e4-989d-e94df5e9735d.jpg)

is there a way to control the axis tick?

**Comment by ryana** [comment]
FWIW, requiring knowing the internals of D3 and running JS seems really odd. I see that pattern a lot in these C3 issues: someone has a problem, and instead of offering a C3 option, 5-30 lines of javascript that manipulating the underlying SVG is with d3 is the accepted solution. I think in the long run that's going to be a huge detriment to the adoption of C3.

For this issue in particular, a "axis.y.tick.integer_only" option would be incredible value. I'd love to provide an extension to C3 for this. I see an example extension [here](https://github.com/masayuki0812/c3/tree/master/extensions/chart-bubble). Is there an extension guide somewhere that can guide me?

Thanks!

**Comment by M4v3R** [comment]
> You can calculate those values after data load, set it to chart.internal.config.axis_y_tick_values and then call chart.flush() to apply new axis values.

Referring to this, because I also had this problem today - doing `flush()` will mess up the animation of data changing, and adding a delay also has some graphical glitches. However, setting `chart.internal.config.axis_y_tick_values` **before** calling `load()` works perfectly. Maybe this will be helpful for someone :).

**Comment by nnabinh** [comment]
Better version:
```
axis: {
        y: {
            tick: {
                format: function(x) { return x % 1 === 0 ? x : ''; }
            }
        }
    }
```

**Comment by DaveSimmons1234** [comment]
Thank you nnabinh - worked a treat.
