### ISSUE TITLE
Tooltip event issues when using multiple “xs” with “groups”

### ISSUE THREAD

**Issue by vbatoufflet** [c3js/c3#719]
Since the changes introduced by the 93703e62efef9029d0172342d6c367582afbccae commit, the display of tooltips does not trigger well when using timeseries X-Axis with multiple `data.xs` on grouped series.

The tooltip is not always shown when moving the cursor over the various series or outside of them.

See http://jsfiddle.net/2u9z7xco/ for an overview.

**Comment by ahalota** [comment]
This issue is not fully resolved.
Can I get the tooltip to behave using data.xs as it does when using data.x?

For example, I have two timeseries data columns (A,B), monthly data for an entire year. Only one of them (A) has daily values for January, so I had to use data.xs in order to let the second group (B) still appear continuous for the entire year while providing the daily values where available.

Now the tooltip has trouble showing up for the remaining months (Feb-Dec), even though here I would wish for the exact same behavior as if I was using data.x only. (At this point, the x's line up perfectly between the two data columns).

**Comment by ahalota** [comment]
As a side note for anyone else in a similar situation, I found that using the option

`line: { 
    connectNull: true
}`

works out just the way I wanted it, without having to use data.xs. More details here: https://github.com/c3js/c3/issues/81
