### ISSUE TITLE
Rescale Y axis when zooming

### ISSUE THREAD

**Issue by yojeek** [c3js/c3#98]
Right now zoom affects only X domain. I'd like to have yMax and yMin axis ticks based only on visible data, not on whole dataset.

Any ideas on how to implement this behviour?

**Comment by knutole** [comment]
Is it possible to zoom only Y axis? Can't seem to find any way.

**Comment by bispaul** [comment]
Same here. Cannot seem to scale the y-axis. The graph zooms scales along x-axis fine.
Can custom codes be attached to scale for dragging the y-axis?

**Comment by odadev** [comment]
Yeah i also wanna zoom only y axis. Is there any solution? o:

**Comment by zarref** [comment]
Yes, me too. I need a solution to zoom bar chart in Y only because I have too distinct values, such: 10 to 2000, so 10 bar doesn't show at all.

Solution 1: Y zoomable.
Solution 2: Have possibility to have logaritmic scale in axis.
Solution 3: Show min quantity of bar pixels when chart is near zero but is higher/lower than zero.

Thanks
